import Mathlib.RingTheory.Coprime.Basic
import Mathlib.Algebra.Polynomial.Coeff
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import LowRankUnivariateSOS.Certificate

noncomputable section

namespace LowRankUnivariateSOS

/-- `scalePair g u` is the pair obtained by multiplying both coordinates of
 `u` by the common factor `g`. In the paper this is the passage from `u'` to
 `g u'` in the `h = 1` case. -/
def scalePair (g : Poly) (u : UPair) : UPair :=
  ⟨g * u.fst, g * u.snd⟩

/-- `perpPair t u = (-t u₂, t u₁)` is the standard syzygy orthogonal to `u`.
 It is the concrete kernel element used throughout the `cone(σ(ker A_u))`
 arguments. -/
def perpPair (t : Poly) (u : UPair) : UPair :=
  ⟨-t * u.snd, t * u.fst⟩

/-- Coordinate formulas for `scalePair`, `perpPair`, and scalar multiplication.
 These are bookkeeping lemmas used to keep later polynomial identities readable. -/
@[simp] theorem scalePair_fst (g : Poly) (u : UPair) :
    (scalePair g u).fst = g * u.fst :=
  rfl

@[simp] theorem scalePair_snd (g : Poly) (u : UPair) :
    (scalePair g u).snd = g * u.snd :=
  rfl

@[simp] theorem perpPair_fst (t : Poly) (u : UPair) :
    (perpPair t u).fst = -t * u.snd :=
  rfl

@[simp] theorem perpPair_snd (t : Poly) (u : UPair) :
    (perpPair t u).snd = t * u.fst :=
  rfl

@[simp] theorem smul_fst (a : ℝ) (u : UPair) :
    (a • u).fst = a • u.fst :=
  rfl

@[simp] theorem smul_snd (a : ℝ) (u : UPair) :
    (a • u).snd = a • u.snd :=
  rfl

/-- The next identities record how `A_u` and `σ` interact with common factors,
 scalar multiples, and the perpendicular syzygy. They are the algebraic
 identities behind the `h = 1` argument in the paper's Section `\ref{sec:h=1}`. -/
@[simp] theorem A_scalePair_left (g : Poly) (u v : UPair) :
    A (scalePair g u) v = g * A u v := by
  simp [scalePair, A]
  ring

@[simp] theorem A_smul_right (a : ℝ) (u v : UPair) :
    A u (a • v) = a • A u v := by
  simp [A, Polynomial.smul_eq_C_mul]
  ring_nf

@[simp] theorem sigma2_smul (a : ℝ) (u : UPair) :
    sigma2 (a • u) = (a ^ 2 : ℝ) • sigma2 u := by
  simp [sigma2, pow_two, Polynomial.smul_eq_C_mul]
  ring_nf

@[simp] theorem sigma2_perpPair (t : Poly) (u : UPair) :
    sigma2 (perpPair t u) = t ^ 2 * sigma2 u := by
  simp [perpPair, sigma2, pow_two]
  ring

@[simp] theorem sigma2_scalePair (g : Poly) (u : UPair) :
    sigma2 (scalePair g u) = g ^ 2 * sigma2 u := by
  simp [scalePair, sigma2, pow_two]
  ring

/-- The perpendicular pair `(-t u₂, t u₁)` lies in `ker(A_{g u})`. This is the
 explicit kernel generator behind the cone terms appearing in condition (C2). -/
theorem inKerA_perpPair_scalePair (g t : Poly) (u : UPair) :
    InKerA (scalePair g u) (perpPair t u) := by
  simp [InKerA, A, scalePair, perpPair]
  ring

/-- The kernel is closed under real scalar multiplication. This is used when
 two identical kernel generators are combined into a single term by scaling with
 `sqrt 2`. -/
theorem inKerA_smul {u w : UPair} (a : ℝ) (hw : InKerA u w) :
    InKerA u (a • w) := by
  rw [InKerA] at hw ⊢
  rw [A_smul_right, hw, smul_zero]

/-- The sum of two kernel-squares lies in `cone(σ(ker(A_u)))`. The proof is
 exactly the cone bookkeeping from the paper: either keep the two generators
 separate, or combine equal ones using a `sqrt 2` rescaling. -/
theorem inSigmaKerCone_of_pair {u w₁ w₂ : UPair}
    (hw₁ : InKerA u w₁) (hw₂ : InKerA u w₂) :
    InSigmaKerCone u (sigma2 w₁ + sigma2 w₂) := by
  by_cases h : w₁ = w₂
  · refine ⟨{(Real.sqrt 2 : ℝ) • w₁}, ?_, ?_⟩
    · intro w hw
      have hw' : w = (Real.sqrt 2 : ℝ) • w₁ := by
        simpa using hw
      rcases hw' with rfl
      exact inKerA_smul (Real.sqrt 2) hw₁
    · subst h
      have hsqrt : (Real.sqrt 2 : ℝ) ^ 2 = 2 := by
        nlinarith [Real.sq_sqrt (show (0 : ℝ) ≤ 2 by norm_num)]
      simp [sigma2_smul, hsqrt, two_smul]
  · refine ⟨{w₁, w₂}, ?_, ?_⟩
    · intro w hw
      have hw' : w = w₁ ∨ w = w₂ := by
        simpa using hw
      rcases hw' with rfl | rfl
      · exact hw₁
      · exact hw₂
    · simp [h]

/-- If `s` is SOS, then `s·σ(u)` belongs to the kernel cone of `A_{g u}`.
 This is the formal version of the paper's observation that an SOS multiple of
 `σ(u')` is generated by squares of explicit kernel vectors. -/
theorem inSigmaKerCone_sos_mul_sigma2 (g s : Poly) (u : UPair)
    (hs : IsSOS s) :
    InSigmaKerCone (scalePair g u) (s * sigma2 u) := by
  rcases hs with ⟨q₁, q₂, rfl⟩
  have hk₁ : InKerA (scalePair g u) (perpPair q₁ u) :=
    inKerA_perpPair_scalePair g q₁ u
  have hk₂ : InKerA (scalePair g u) (perpPair q₂ u) :=
    inKerA_perpPair_scalePair g q₂ u
  have hcone :
      InSigmaKerCone (scalePair g u)
        (sigma2 (perpPair q₁ u) + sigma2 (perpPair q₂ u)) :=
    inSigmaKerCone_of_pair hk₁ hk₂
  have hsigma :
      sigma2 (perpPair q₁ u) + sigma2 (perpPair q₂ u) = (q₁ ^ 2 + q₂ ^ 2) * sigma2 u := by
    simp [sigma2, pow_two]
    ring
  rw [hsigma] at hcone
  simpa using hcone

/-- Bézout surjectivity: if `u₁` and `u₂` are coprime, then every polynomial
 lies in `im(A_u)`. This is the Lean incarnation of
 `\Cref{lem:coprime_kernel}` specialized to the univariate rank-2 setting. -/
theorem inImageA_of_isCoprime (u : UPair) (hu : IsCoprime u.fst u.snd) (q : Poly) :
    InImageA u q := by
  rcases hu with ⟨a, b, hab⟩
  refine ⟨⟨a * q, b * q⟩, ?_⟩
  calc
    A u ⟨a * q, b * q⟩ = (a * u.fst + b * u.snd) * q := by
      simp [A]
      ring
    _ = q := by rw [hab, one_mul]

/-- The scaled version of Bézout surjectivity: every multiple `g q` lies in
 `im(A_{g u})` when the reduced pair `u` is coprime. -/
theorem inImageA_mul_of_isCoprime (g q : Poly) (u : UPair)
    (hu : IsCoprime u.fst u.snd) :
    InImageA (scalePair g u) (g * q) := by
  rcases inImageA_of_isCoprime u hu q with ⟨v, hv⟩
  refine ⟨v, ?_⟩
  simp [A_scalePair_left, hv]

/-- This packages the paper's `h = 1` sufficient condition. If
 `p = g q + s σ(u)` with `u` coprime and `s` SOS, then `p` lies in
 `im(A_{g u}) + cone(σ(ker(A_{g u})))`, which is precisely condition (C2). -/
theorem inImagePlusSigmaKerCone_of_h1_data
    (g p q s : Poly) (u : UPair)
    (hu : IsCoprime u.fst u.snd)
    (hs : IsSOS s)
    (hp : p = g * q + s * sigma2 u) :
    InImagePlusSigmaKerCone (scalePair g u) p := by
  rcases inImageA_mul_of_isCoprime g q u hu with ⟨v, hv⟩
  rcases inSigmaKerCone_sos_mul_sigma2 g s u hs with ⟨ws, hwsker, hsum⟩
  refine ⟨v, ws, hwsker, ?_⟩
  rw [hp, hv, hsum]

end LowRankUnivariateSOS
