import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Data.Real.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset

noncomputable section

namespace LowRankUnivariateSOS

open scoped BigOperators

abbrev Poly := Polynomial ℝ

instance : GCDMonoid Poly := EuclideanDomain.gcdMonoid Poly

/-- `UPair` is the rank-2 factor variable `\vec u = (u₁,u₂)` from the paper.
 We work throughout with pairs because the no-spurious-SOCP theorem is proved by
 reducing the general rank-`r` statement to the case `r = 2`. -/
structure UPair where
  fst : Poly
  snd : Poly

instance : DecidableEq UPair := by
  classical
  infer_instance

namespace UPair

/-- Extensionality for polynomial pairs. This is the basic way we identify two
 candidate factorizations once their two coordinates agree. -/
@[ext] theorem ext {u v : UPair} (hfst : u.fst = v.fst) (hsnd : u.snd = v.snd) : u = v := by
  cases u
  cases v
  cases hfst
  cases hsnd
  rfl

instance : Zero UPair where
  zero := ⟨0, 0⟩

instance : Add UPair where
  add u v := ⟨u.fst + v.fst, u.snd + v.snd⟩

instance : Neg UPair where
  neg u := ⟨-u.fst, -u.snd⟩

instance : Sub UPair where
  sub u v := ⟨u.fst - v.fst, u.snd - v.snd⟩

instance : SMul ℝ UPair where
  smul a u := ⟨a • u.fst, a • u.snd⟩

end UPair

/-- The quadratic map `σ(\vec u) = u₁² + u₂²` from the paper. This is the SOS
 polynomial represented by the rank-2 factor `u`. -/
def sigma2 (u : UPair) : Poly :=
  u.fst ^ 2 + u.snd ^ 2

/-- The linear map `A_u(v) = u₁ v₁ + u₂ v₂` introduced in the paper before
 Definition `\ref{def:socp}`. It packages the first-order variation of `σ`. -/
def A (u v : UPair) : Poly :=
  u.fst * v.fst + u.snd * v.snd

/-- The primal residual `σ(u) - p`. Vanishing of this residual is exactly the
 statement that `u` is a global minimizer for the polynomial `p`. -/
def residual (p : Poly) (u : UPair) : Poly :=
  sigma2 u - p

/-- `IsSOS p` is the concrete rank-2 SOS representation used in the paper:
 `p = q₁² + q₂²`. Since every nonnegative univariate polynomial is a sum of two
 squares, this is the right notion of feasibility for the main theorem. -/
def IsSOS (p : Poly) : Prop :=
  ∃ q₁ q₂ : Poly, p = q₁ ^ 2 + q₂ ^ 2

/-- Membership in the image of `A_u`. In the paper this is the condition
 `q ∈ im(A_u)`. -/
def InImageA (u : UPair) (q : Poly) : Prop :=
  ∃ v : UPair, A u v = q

/-- Membership in the kernel of `A_u`. In the paper this is `v ∈ ker(A_u)`. -/
def InKerA (u v : UPair) : Prop :=
  A u v = 0

/-- Membership in the cone generated by `σ(ker(A_u))`. This is the cone term
 in the paper's sufficient condition (C2): `im(A_u) + cone(σ(ker(A_u)))`. -/
def InSigmaKerCone (u : UPair) (q : Poly) : Prop :=
  ∃ ws : Finset UPair, (∀ w ∈ ws, InKerA u w) ∧ q = ws.sum sigma2

end LowRankUnivariateSOS
